version: '3.5'

services:
    perl:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: perl-5.24.3
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:latest
            cache_from:
                - base_container:latest
                - alpine:3.6
            context: .
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: perl-5.24.3:latest
