version: '3.5'

services:
    perl:
        build:
            args:
                FROM_BASE: base_container:20180217
                CONTAINER_VERSION: 1.0.2
            context: .
            cache_from:
                - base_container:20180217
                - alpine:3.6
        image: perl-5.24.3:20180205

    base:
        build:
            args:
                FROM_BASE: alpine:3.6
                CONTAINER_VERSION: 1.0.2
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180217
