version: '3.5'

services:
    perl:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: perl-5.24.3
                CONTAINER_VERSION: 1.0.8
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180329
            cache_from:
                - base_container:20180329
                - alpine:3.6
            context: .
            dockerfile: Dockerfile
        image: perl-5.24.3:20180329
