version: '3.3'

services:
    perl:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: perl
                FROM_BASE: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}base_container:${BASE_TAG:-latest}
                PERL_VERSION: ${PERL_VERSION:-5.26.2}
            cache_from:
                - ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: perl
        container_name: perl
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}perl/${PERL_VERSION:-5.26.2}:${CONTAINER_TAG:-latest}
