version: '3.5'

services:
    perl:
        build:
            context: .
            cache_from:
                - base_container:20180210
                - alpine:3.6
#        depends_on:
#            - base_container:20180210
        image: perl-5.24.3:20180205
