version: '3.5'

services:
    perl:
        build:
            context: .
            cache_from:
                - base_container:20180210
                - alpine:3.6
        depends_on:
            - base
        image: perl-5.24.3:20180205

    base:
        build:
            args:
                CODE_VERSION: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180210
