version: '3.3'

services:
    perl:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION}"
                CONTAINER_NAME: perl-5.24.3
                CONTAINER_VERSION: 3.0.0
                FROM_BASE: base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.7
                - base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: perl
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: perl-5.24.3:${CONTAINER_TAG:-latest}
